export type ToolCategory = 'image' | 'developer' | 'text' | 'utility';

export interface ToolItem {
  id: string;
  slug: string;
  name: string;
  shortDescription: string;
  category: ToolCategory;
  categoryName: string;
  iconName: string;
  badge: string;
  popular?: boolean;
  metaTitle: string;
  metaDescription: string;
  longDescription: string;
  howToSteps: { step: number; title: string; text: string }[];
  features: string[];
  faqs: { question: string; answer: string }[];
  keywords: string[];
}

export const CATEGORIES: { id: ToolCategory; name: string; description: string; count?: number }[] = [
  {
    id: 'image',
    name: 'Image Tools',
    description: 'Compress, convert, resize, crop, and generate meme graphics directly in your browser using HTML5 Canvas.',
  },
  {
    id: 'developer',
    name: 'Developer & Code',
    description: 'JSON formatters, regex analyzers, cryptographic hashes, UUID generators, and code minifiers.',
  },
  {
    id: 'text',
    name: 'Text & Content',
    description: 'Markdown editors, case transformers, duplicate line strippers, and Lorem Ipsum generators.',
  },
  {
    id: 'utility',
    name: 'Everyday Utilities',
    description: 'Word counters, password entropy generators, BMI calculators, unit converters, and age counters.',
  },
];

export const TOOLS_DATA: ToolItem[] = [
  // --- IMAGE TOOLS ---
  {
    id: 'image-compressor',
    slug: 'image-compressor',
    name: 'Image Compressor',
    shortDescription: 'Compress JPEG, PNG, and WebP images locally with custom quality and max dimension controls.',
    category: 'image',
    categoryName: 'Image Tools',
    iconName: 'Minimize2',
    badge: 'Privacy-First',
    popular: true,
    keywords: ['image compressor', 'compress jpg', 'reduce png size', 'webp compression', 'client side image optimizer'],
    metaTitle: 'Free Client-Side Image Compressor - Compress Images Locally',
    metaDescription: 'Compress JPEG, PNG, and WebP images in your browser without uploading to any server. Reduce file sizes quickly while preserving visual sharpness.',
    longDescription: 'Our free client-side Image Compressor utilizes the browser HTML5 Canvas API and native compression algorithms to drastically decrease image file sizes without sacrificing essential perceptual clarity. Unlike traditional image optimization portals that transfer your private photos across unvetted cloud networks, our processor operates completely within your local device memory. Whether you are prepping high-resolution photography for web publishing, optimizing portfolio images, or compressing documents for email attachments, this tool gives you granular control over lossy quality quantization, maximum output dimension bounding, and instant byte-saving calculations.',
    howToSteps: [
      { step: 1, title: 'Upload Your Image', text: 'Drag and drop your JPEG, PNG, or WebP file into the upload zone or tap to select from your local drive.' },
      { step: 2, title: 'Adjust Compression & Dimensions', text: 'Fine-tune the compression quality slider (1-100%) and optionally specify maximum width or height constraints.' },
      { step: 3, title: 'Inspect Savings & Download', text: 'Review the instant before-and-after byte comparison, visual quality preview, and click Download to save the optimized file.' },
    ],
    features: [
      '100% In-browser execution with zero network transmission',
      'Supports JPEG, PNG, and modern WebP formats',
      'Real-time file size comparison with calculated reduction percentage',
      'Preserves image aspect ratios with intelligent maximum dimension bounding',
      'No file size ceilings or daily usage caps',
    ],
    faqs: [
      { question: 'Are my uploaded images saved on your servers?', answer: 'No. All processing occurs strictly in your device memory via standard browser Canvas APIs. Files are never uploaded, logged, or sent across any network.' },
      { question: 'What image formats can I compress?', answer: 'You can compress JPEG, PNG, and WebP files. WebP and JPEG generally offer the highest compression ratios for photographic content.' },
      { question: 'How much file size reduction can I expect?', answer: 'Depending on the starting image format and the compression level chosen, users frequently observe 50% to 85% reduction in file size with negligible perceptible visual degradation.' },
    ],
  },
  {
    id: 'image-converter',
    slug: 'image-converter',
    name: 'Image Format Converter',
    shortDescription: 'Convert images between PNG, JPEG, WebP, and BMP formats instantly inside your browser.',
    category: 'image',
    categoryName: 'Image Tools',
    iconName: 'RefreshCw',
    badge: 'Lossless & Fast',
    popular: true,
    keywords: ['image converter', 'png to jpg', 'jpg to webp', 'convert image format online', 'browser image converter'],
    metaTitle: 'Client-Side Image Format Converter - PNG, JPG, WebP',
    metaDescription: 'Convert images between PNG, JPG, WebP, and BMP seamlessly in your web browser. Free, private, and instantaneous with no server uploads.',
    longDescription: 'Transform visual assets across contemporary web raster formats with our zero-install Image Format Converter. Powered directly by browser hardware acceleration and the HTML5 2D rendering context, this utility enables seamless transcoding between PNG, JPEG, WebP, and BMP formats. Optimize modern responsive websites by turning heavy legacy PNGs or JPEGs into compact WebP graphics, or extract transparent PNG layers into universal JPEG files with customizable background matte colors. Everything is processed locally on your client machine.',
    howToSteps: [
      { step: 1, title: 'Choose Target Image', text: 'Drag and drop an image file or browse from your desktop or mobile device.' },
      { step: 2, title: 'Select Target Output Format', text: 'Pick your desired destination format: WebP, PNG, JPEG, or BMP.' },
      { step: 3, title: 'Set Quality and Convert', text: 'Configure compression quality for lossy targets and download the converted image immediately.' },
    ],
    features: [
      'Multi-format support: PNG, JPEG, WebP, BMP',
      'Quality slider for granular lossy compression targets',
      'Instant canvas rasterization with color profile preservation',
      'High-resolution output without arbitrary dimension downsampling',
      '100% private client-side processing',
    ],
    faqs: [
      { question: 'Why should I convert images to WebP?', answer: 'WebP provides superior lossless and lossy compression for web images, often resulting in 25-35% smaller file sizes compared to PNGs and JPEGs while preserving transparency and clarity.' },
      { question: 'Will converting PNG to JPEG retain transparency?', answer: 'JPEG does not support alpha channel transparency. When converting a transparent PNG to JPEG, transparent areas will default to a solid white background.' },
      { question: 'Is there a limit on how many images I can convert?', answer: 'No! Because all computations run locally on your browser hardware, there are no artificial hourly or daily conversion quotas.' },
    ],
  },
  {
    id: 'image-resizer',
    slug: 'image-resizer',
    name: 'Image Resizer & Cropper',
    shortDescription: 'Resize dimensions by pixels or percentage, lock aspect ratio, rotate, and flip images with ease.',
    category: 'image',
    categoryName: 'Image Tools',
    iconName: 'Crop',
    badge: 'Pixel Precision',
    popular: false,
    keywords: ['image resizer', 'resize picture', 'crop image online', 'scale photo pixels', 'rotate image in browser'],
    metaTitle: 'Image Resizer & Dimension Scale Tool - Free & Client-Side',
    metaDescription: 'Scale, resize, rotate, and transform image dimensions online. Lock aspect ratios or set custom pixel dimensions directly in your browser.',
    longDescription: 'Resize and transform your photos with pixel-perfect precision using our browser-based Image Resizer. Tailor digital photos for social media banners, website thumbnails, avatar profile pictures, or presentation slides. The tool supports proportional aspect ratio constraints, custom width and height overrides, percentage scaling, 90-degree orthogonal rotations, and horizontal or vertical mirroring. High-quality bicubic canvas interpolation ensures resampled imagery retains smooth gradients and crisp edges.',
    howToSteps: [
      { step: 1, title: 'Import Graphic', text: 'Select an image from your device or drag it onto the editing canvas.' },
      { step: 2, title: 'Define Dimensions or Rotation', text: 'Enter new pixel dimensions (with optional aspect lock), or use percentage scaling and rotation tools.' },
      { step: 3, title: 'Export Resized Asset', text: 'Preview the resulting canvas transformation and save your new image with a single click.' },
    ],
    features: [
      'Flexible input modes: absolute pixel dimensions or percentage scaling',
      'Aspect ratio constraint lock with automatic complementary axis calculation',
      'Orthogonal 90°, 180°, and 270° rotation controls',
      'Horizontal and vertical canvas flip utilities',
      'Zero server dependencies; safe for confidential and personal graphics',
    ],
    faqs: [
      { question: 'What does locking aspect ratio do?', answer: 'When aspect ratio is locked, modifying the width automatically updates the height proportionally (and vice versa) to prevent your image from becoming squished or stretched.' },
      { question: 'Does resizing reduce image quality?', answer: 'Downscaling reduces pixel dimensions while maintaining sharpness. Upscaling beyond the original image resolution cannot invent new detail, but our smooth canvas interpolation prevents harsh pixelation.' },
      { question: 'Can I rotate and resize simultaneously?', answer: 'Yes, rotation transformations and dimension scalers can be configured in a single pass before final export.' },
    ],
  },
  {
    id: 'image-to-base64',
    slug: 'image-to-base64',
    name: 'Image to Base64 Converter',
    shortDescription: 'Convert any image to Base64 Data URL, HTML <img> tag, or CSS background-image snippet.',
    category: 'image',
    categoryName: 'Image Tools',
    iconName: 'Code',
    badge: 'Dev Utility',
    popular: false,
    keywords: ['image to base64', 'data uri generator', 'base64 image encoder', 'embed image in css', 'inline base64 string'],
    metaTitle: 'Image to Base64 Converter - Data URI Generator',
    metaDescription: 'Encode images into Base64 Data URIs, HTML image tags, and CSS background-image code snippets. Completely client-side and secure.',
    longDescription: 'Inlining raster assets directly into HTML, CSS, or JSON configuration payloads eliminates unnecessary HTTP roundtrips for small icons, placeholders, and email signatures. Our Image to Base64 Converter reads your local image through the browser FileReader API and produces RFC 2397-compliant Data URLs in milliseconds. Easily copy the raw Base64 string, an HTML <img> tag with preset dimensions, or a CSS background-image snippet ready for immediate insertion into your codebase.',
    howToSteps: [
      { step: 1, title: 'Upload Asset', text: 'Drop your SVG, PNG, JPEG, or WebP file into the encoder.' },
      { step: 2, title: 'Select Code Format', text: 'Choose between Raw Base64 string, Data URI, HTML tag, or CSS background snippet.' },
      { step: 3, title: 'Copy to Clipboard', text: 'Review the string payload length and copy the formatted code directly into your code editor.' },
    ],
    features: [
      'Generates Raw Base64, RFC 2397 Data URI, HTML <img>, and CSS snippets',
      'Calculates exact encoded character count and estimated payload overhead',
      'Live image preview ensuring correct MIME type attribution',
      'One-tap clipboard copy buttons for each output format',
      'Works completely offline without uploading assets to remote servers',
    ],
    faqs: [
      { question: 'What is a Base64 Data URI?', answer: 'A Data URI allows image data to be embedded directly into web documents as an ASCII string (e.g. data:image/png;base64,...), eliminating the need for a standalone asset URL.' },
      { question: 'When should I use Base64 images?', answer: 'Base64 inlining is best suited for small icons, loaders, single-page offline apps, and email templates where eliminating external HTTP requests speeds up initial paint.' },
      { question: 'How much larger is a Base64 string compared to binary files?', answer: 'Base64 encoding increases data footprint by approximately 33% due to representing 3 binary bytes as 4 ASCII characters.' },
    ],
  },
  {
    id: 'favicon-generator',
    slug: 'favicon-generator',
    name: 'Favicon & App Icon Generator',
    shortDescription: 'Create complete multi-size icon packs (16x16, 32x32, 180x180 Apple Touch, 512x512 PWA) with ZIP download.',
    category: 'image',
    categoryName: 'Image Tools',
    iconName: 'Layers',
    badge: 'PWA Ready',
    popular: true,
    keywords: ['favicon generator', 'apple touch icon generator', 'pwa icon pack', 'generate favicon online', 'ico converter'],
    metaTitle: 'Favicon & PWA Icon Pack Generator - Free & Browser-Based',
    metaDescription: 'Generate a complete suite of browser favicons, Apple touch icons, and Android PWA icons from any image. Download individual files or all as a ZIP.',
    longDescription: 'Building a modern web application requires delivering correctly sized favicons for standard desktop tabs, retina displays, bookmark bars, iOS home screen web clips, and Android PWA manifests. Our Favicon & App Icon Generator accepts any source image and renders an exhaustive package of standardized dimensions: 16x16, 32x32, 48x48, 64x64, 180x180 (Apple Touch Icon), 192x192 (Android PWA), and 512x512 (Splash Screen). Download assets individually or package the entire bundle into a single ZIP archive alongside ready-to-paste HTML header link tags.',
    howToSteps: [
      { step: 1, title: 'Upload Logo or Artwork', text: 'Select a square or high-resolution graphic (SVG or PNG recommended).' },
      { step: 2, title: 'Review Generated Sizes', text: 'Inspect the live rendered previews across 16x16, 32x32, 180x180, and 512x512 specifications.' },
      { step: 3, title: 'Download Bundle & Copy HTML', text: 'Click "Download All as ZIP" and paste the provided HTML snippet into your website <head> tag.' },
    ],
    features: [
      'Generates 7 essential web and mobile icon specifications',
      'Provides copy-paste HTML <link rel="icon"> code snippets',
      'Client-side ZIP packaging via JSZip with zero server upload',
      'Bicubic downsampling for ultra-crisp icon rendering at 16px and 32px',
      '100% private and instantaneous',
    ],
    faqs: [
      { question: 'What size image should I upload?', answer: 'For crisp results across all device densities, upload a square image of at least 512x512 pixels with a transparent background.' },
      { question: 'What HTML tags are needed for modern favicons?', answer: 'Modern web standards recommend a standard favicon.ico or 32x32 PNG for desktop tabs, an apple-touch-icon (180x180) for iOS devices, and a web app manifest containing 192x192 and 512x512 icons.' },
      { question: 'Can I download individual icon sizes without downloading the full ZIP?', answer: 'Yes, each icon resolution includes an individual direct PNG download button.' },
    ],
  },
  {
    id: 'meme-generator',
    slug: 'meme-generator',
    name: 'Meme Generator',
    shortDescription: 'Overlay classic top and bottom impact text on your photos with customizable outlines, fonts, and colors.',
    category: 'image',
    categoryName: 'Image Tools',
    iconName: 'Smile',
    badge: 'Fun & Creative',
    popular: false,
    keywords: ['meme generator', 'add text to image', 'caption maker', 'impact font meme', 'client side meme creator'],
    metaTitle: 'Fast Meme Generator - In-Browser Meme Maker',
    metaDescription: 'Make classic memes and image captions online in seconds. Add customizable top and bottom text with stroke outlines and instant downloads.',
    longDescription: 'Create viral humor, social commentary, or community graphics in seconds with our client-side Meme Generator. Featuring classic Impact styling with thick legible black outlines, custom font size scalers, letter spacing options, and flexible text position adjustments. Upload your own photography or choose from built-in template canvases. Because the text compositing runs on an in-memory HTML5 canvas, you can craft memes on mobile or desktop without watermarks, subscriptions, or telemetry.',
    howToSteps: [
      { step: 1, title: 'Load Image Canvas', text: 'Upload your photo or choose one of our clean starter gradient backgrounds.' },
      { step: 2, title: 'Type Top & Bottom Captions', text: 'Input your punchlines. Adjust text color, outline thickness, font size, and uppercase casing.' },
      { step: 3, title: 'Save & Share', text: 'Preview your finished meme in real-time and download the high-resolution PNG.' },
    ],
    features: [
      'Real-time WYSIWYG canvas typography compositing',
      'Custom text stroke outline thickness and fill colors',
      'Uppercase capitalization toggle and font size slider',
      'No watermarks, no account requirements, and no branding logos',
      'Instant PNG export directly to your photo library or download folder',
    ],
    faqs: [
      { question: 'Does this meme generator add watermarks?', answer: 'No. We believe in unencumbered utility tools. Generated memes are completely watermark-free and belong entirely to you.' },
      { question: 'Can I adjust text positioning?', answer: 'Yes, you can tweak font sizes, padding offsets, and uppercase styling for both top and bottom text layers independently.' },
      { question: 'Do my pictures get saved to a public feed?', answer: 'Never. Processing happens strictly in your browser. Nothing is ever saved to a remote server or public gallery.' },
    ],
  },

  // --- DEVELOPER & CODE TOOLS ---
  {
    id: 'json-formatter',
    slug: 'json-formatter',
    name: 'JSON Formatter & Validator',
    shortDescription: 'Format, beautify, minify, and validate JSON data with clear syntax error detection and hierarchy tree view.',
    category: 'developer',
    categoryName: 'Developer & Code',
    iconName: 'Braces',
    badge: 'Essential',
    popular: true,
    keywords: ['json formatter', 'json validator', 'beautify json', 'minify json', 'json lint', 'parse json online'],
    metaTitle: 'Online JSON Formatter & Validator - Prettify & Lint JSON',
    metaDescription: 'Validate, format, indent, and minify JSON data with precise line-by-line syntax error diagnostics. 100% private and client-side.',
    longDescription: 'Debugging API responses, analyzing database payloads, and formatting nested configuration files requires a robust parser that respects confidential credentials. Our JSON Formatter & Validator checks JSON strings against strict RFC 8259 specifications, outputting beautifully indented structures with customizable 2-space, 4-space, or tab layouts. If your syntax contains missing quotes, trailing commas, or unbalanced brackets, our diagnostic engine highlights the exact character index and error description.',
    howToSteps: [
      { step: 1, title: 'Paste Raw JSON', text: 'Paste your JSON payload into the input editor or load an example sample.' },
      { step: 2, title: 'Choose Indentation or Minify', text: 'Click "Format (2 Spaces)", "Format (4 Spaces)", or "Minify" to clean up unnecessary whitespace.' },
      { step: 3, title: 'Copy or Download', text: 'Copy the sanitized JSON string to your clipboard or download it as a .json file.' },
    ],
    features: [
      'Instant syntax validation with precise error message reporting',
      'Configurable indentation: 2 spaces, 4 spaces, or compact minification',
      'Key and value count statistics with byte size indicators',
      'One-click sample loader for testing',
      'Zero server round-trips: perfect for proprietary tokens and private customer records',
    ],
    faqs: [
      { question: 'Is my JSON data secure when using this validator?', answer: 'Yes, 100%. Parsing and formatting are performed entirely within your browser via JavaScript Native JSON parser. No data is transmitted across the internet.' },
      { question: 'What causes JSON parse errors most frequently?', answer: 'The most common culprits are trailing commas after the last array/object element, unescaped double quotes inside strings, or single quotes instead of double quotes.' },
      { question: 'Can I minify large JSON files?', answer: 'Yes. Minifying strips out tabs, spaces, and newline characters to minimize data payload weight for production web transfers.' },
    ],
  },
  {
    id: 'json-csv-converter',
    slug: 'json-csv-converter',
    name: 'JSON to CSV / CSV to JSON Converter',
    shortDescription: 'Convert between JSON arrays and CSV spreadsheets bidirectionally with automatic header detection and preview table.',
    category: 'developer',
    categoryName: 'Developer & Code',
    iconName: 'FileSpreadsheet',
    badge: 'Bidirectional',
    popular: true,
    keywords: ['json to csv', 'csv to json', 'convert json to excel', 'convert spreadsheet to json', 'csv parser online'],
    metaTitle: 'JSON to CSV and CSV to JSON Converter - Free & Browser-Based',
    metaDescription: 'Convert JSON data to CSV spreadsheets and CSV back to JSON bidirectionally. Includes live table preview and delimiter options with zero server uploads.',
    longDescription: 'Bridging the gap between software APIs and spreadsheet applications like Microsoft Excel or Google Sheets is effortless with our bidirectional JSON to CSV Converter. Paste an array of JSON objects to generate RFC 4180-compliant CSV rows with automatic header extraction, quote escaping, and custom delimiter support (comma, semicolon, tab). Conversely, paste raw tabular data to receive cleanly structured JSON objects ready for database insertion or REST API payload crafting.',
    howToSteps: [
      { step: 1, title: 'Select Conversion Direction', text: 'Toggle between "JSON to CSV" or "CSV to JSON" mode.' },
      { step: 2, title: 'Input Data', text: 'Paste your structured source code or load an interactive demo dataset.' },
      { step: 3, title: 'Preview & Export', text: 'Inspect the generated data in our live interactive table preview and download the resulting file.' },
    ],
    features: [
      'Bidirectional conversion: JSON <-> CSV',
      'Configurable delimiter: comma (,), semicolon (;), or tab (TSV)',
      'Automatic column header mapping from dynamic object keys',
      'Interactive data table preview displaying parsed records',
      'Export directly to .csv or .json files with single-click download',
    ],
    faqs: [
      { question: 'Can it convert nested JSON objects into CSV?', answer: 'Nested objects are serialized or flattened into string representations so tabular spreadsheet columns maintain data integrity.' },
      { question: 'Does this handle quotes and commas inside text fields?', answer: 'Yes. Values containing commas, line breaks, or quotation marks are properly enclosed in double quotes according to standard RFC 4180 CSV specifications.' },
      { question: 'Can I open the generated CSV directly in Microsoft Excel?', answer: 'Yes, the exported CSV uses UTF-8 encoding and standard formatting fully compatible with Excel, Google Sheets, Numbers, and database imports.' },
    ],
  },
  {
    id: 'base64-encoder-decoder',
    slug: 'base64-encoder-decoder',
    name: 'Base64 Encoder & Decoder',
    shortDescription: 'Encode and decode plain text or binary strings with UTF-8 character support and URL-safe Base64 mode.',
    category: 'developer',
    categoryName: 'Developer & Code',
    iconName: 'Binary',
    badge: 'UTF-8 Safe',
    popular: false,
    keywords: ['base64 encoder', 'base64 decoder', 'decode base64 text', 'url safe base64', 'ascii to base64'],
    metaTitle: 'Base64 Encode & Decode Online - UTF-8 & URL-Safe',
    metaDescription: 'Encode plain text to Base64 and decode Base64 strings to readable text. Supports international UTF-8 characters and URL-safe encoding.',
    longDescription: 'Base64 encoding is widely utilized in web architecture, authorization headers, data transfers, and email protocols to represent binary information in an ASCII string format. Our Base64 Encoder & Decoder features full international UTF-8 compatibility, handling special multilingual characters, symbols, and emojis without encoding corruption. Toggle URL-safe mode to replace standard plus (+) and slash (/) symbols with hyphens and underscores for clean web query strings.',
    howToSteps: [
      { step: 1, title: 'Select Mode', text: 'Choose either "Encode" (Text to Base64) or "Decode" (Base64 to Text).' },
      { step: 2, title: 'Paste Input Text', text: 'Enter or paste your text into the primary editor panel.' },
      { step: 3, title: 'Inspect & Copy', text: 'View the instant output with live character counts and copy to clipboard.' },
    ],
    features: [
      'Dual-mode operation: Instant Encode and Decode',
      'Full UTF-8 unicode encoding support preventing broken character encoding',
      'URL-Safe Base64 mode replacing + and / with - and _',
      'Character and byte size indicators for both input and output strings',
      'Immediate client-side execution with zero data storage',
    ],
    faqs: [
      { question: 'Is Base64 an encryption method?', answer: 'No. Base64 is an encoding scheme designed for data serialization, not encryption. Anyone can decode a Base64 string without a key. Never use Base64 alone to protect sensitive passwords.' },
      { question: 'What is URL-Safe Base64?', answer: 'Standard Base64 uses + and / which have special meanings in URLs. URL-Safe Base64 substitutes + with - and / with _, making the string safe to pass in web links and cookies.' },
      { question: 'Does this tool support emojis and non-English scripts?', answer: 'Yes! Our implementation utilizes a robust UTF-8 encoder layer that prevents common latin1 JavaScript encoding crashes.' },
    ],
  },
  {
    id: 'regex-tester',
    slug: 'regex-tester',
    name: 'Regex Tester & Matcher',
    shortDescription: 'Test regular expressions with real-time match highlighting, capture group extraction, and common pattern presets.',
    category: 'developer',
    categoryName: 'Developer & Code',
    iconName: 'Search',
    badge: 'Live Syntax',
    popular: true,
    keywords: ['regex tester', 'regular expression evaluator', 'regex matcher', 'regex cheat sheet', 'javascript regex tool'],
    metaTitle: 'Regex Tester & Match Highlighter - Client-Side Regular Expression Tool',
    metaDescription: 'Test regular expressions in real-time with visual match highlighting, capture group inspectors, regex flags, and prebuilt syntax presets.',
    longDescription: 'Crafting and troubleshooting regular expressions can be challenging without immediate visual verification. Our Regex Tester provides a live, interactive environment that evaluates your regular expression patterns against test text on every keystroke. Inspect individual match offsets, capture groups, and match counts with clear, high-contrast visual badges. Includes handy presets for common regex needs such as emails, URLs, dates, phone numbers, and IPv4 addresses.',
    howToSteps: [
      { step: 1, title: 'Enter Regular Expression', text: 'Type your regex pattern in the expression field and select your target flags (g, i, m, s).' },
      { step: 2, title: 'Provide Test Corpus', text: 'Paste the string or document you want to evaluate against.' },
      { step: 3, title: 'Examine Highlights & Groups', text: 'View marked match instances in the preview window and inspect capture groups in the detailed table below.' },
    ],
    features: [
      'Interactive visual match highlighting with individual capture group inspects',
      'Toggle standard JavaScript regex flags: Global (g), Case-Insensitive (i), Multiline (m), DotAll (s)',
      'Detailed match statistics: total matches, index positions, and group breakdowns',
      'Library of quick-load pattern presets (Email, URL, IP address, UUID, Date)',
      'Syntax error protection preventing application freezes on invalid expressions',
    ],
    faqs: [
      { question: 'What regex engine is used?', answer: 'This tool uses the native JavaScript RegExp engine built into your web browser, ensuring 100% fidelity with front-end code and Node.js execution environments.' },
      { question: 'What does the "g" (global) flag do?', answer: 'The global flag instructs the regex engine to locate all matching occurrences throughout the entire text rather than stopping after the first match.' },
      { question: 'What happens if my regular expression is invalid?', answer: 'The tester catches syntax exceptions instantly and displays a friendly error banner without interrupting your typing workflow.' },
    ],
  },
  {
    id: 'markdown-editor',
    slug: 'markdown-editor',
    name: 'Markdown Live Editor & Previewer',
    shortDescription: 'Write Markdown with side-by-side live HTML preview, formatting toolbar, word count, and HTML/MD export.',
    category: 'developer',
    categoryName: 'Developer & Code',
    iconName: 'FileCode',
    badge: 'Split Screen',
    popular: false,
    keywords: ['markdown editor', 'markdown live preview', 'md to html', 'markdown viewer', 'online markdown tool'],
    metaTitle: 'Markdown Live Editor & HTML Previewer - Free & In-Browser',
    metaDescription: 'Draft and preview Markdown documents with live split-screen rendering, instant HTML compilation, word counting, and export options.',
    longDescription: 'Draft documentation, technical blog articles, and README files with our split-screen Markdown Live Editor. As you write in the left pane, the right preview window renders your formatted typography, tables, code blocks, lists, blockquotes, and headings in real time. Features a quick-action formatting toolbar, word and character meters, and one-tap export options to download your document as clean raw Markdown or compiled HTML.',
    howToSteps: [
      { step: 1, title: 'Type or Paste Markdown', text: 'Draft content in the input editor or load our formatted markdown template.' },
      { step: 2, title: 'Use Quick Formatting Toolbar', text: 'Quickly insert headings, bold text, links, code blocks, or tables using the toolbar icons.' },
      { step: 3, title: 'Export or Copy', text: 'Copy the compiled HTML markup or download the document as a .md or .html file.' },
    ],
    features: [
      'Real-time split-screen live preview with synchronized styling',
      'Toolbar shortcuts for bold, italic, headings, lists, blockquotes, and code',
      'Accurate word and character counters',
      'Export options for both raw Markdown (.md) and compiled HTML (.html)',
      '100% client-side with persistent session auto-save in memory',
    ],
    faqs: [
      { question: 'What Markdown flavor is supported?', answer: 'Our editor adheres to standard GitHub Flavored Markdown (GFM), including support for strike-through, tables, task lists, and fenced code blocks.' },
      { question: 'Can I export the compiled HTML directly?', answer: 'Yes! You can view the raw HTML markup, copy it to your clipboard with one click, or download a standalone HTML file.' },
      { question: 'Is my drafted text saved if I refresh?', answer: 'Drafted content is maintained in your active browser session so you do not lose accidental edits.' },
    ],
  },
  {
    id: 'hash-generator',
    slug: 'hash-generator',
    name: 'Cryptographic Hash Generator',
    shortDescription: 'Generate MD5, SHA-1, SHA-256, SHA-384, and SHA-512 hashes simultaneously using the native Web Crypto API.',
    category: 'developer',
    categoryName: 'Developer & Code',
    iconName: 'ShieldCheck',
    badge: 'Hardware Crypto',
    popular: true,
    keywords: ['hash generator', 'sha256 generator', 'md5 hash online', 'sha1 generator', 'web crypto hash'],
    metaTitle: 'Hash Generator - MD5, SHA-1, SHA-256, SHA-512 Online',
    metaDescription: 'Generate cryptographic checksums and hashes (MD5, SHA-1, SHA-256, SHA-384, SHA-512) directly in your browser with hardware Web Crypto acceleration.',
    longDescription: 'Verify file integrity, generate cryptographic fingerprints, or validate message digests with our multi-algorithm Hash Generator. Powered by the W3C Web Cryptography API, hash computations run directly on your device CPU with zero transmission of input text across any network. Generates SHA-256, SHA-1, SHA-384, SHA-512, and classic MD5 hashes concurrently with uppercase and lowercase hex toggle and individual one-click copy buttons.',
    howToSteps: [
      { step: 1, title: 'Enter Plaintext or Secret', text: 'Type or paste the string you wish to hash into the input area.' },
      { step: 2, title: 'Review Generated Hashes', text: 'All algorithms compute immediately in parallel, displaying their respective hex digests.' },
      { step: 3, title: 'Copy Desired Hash', text: 'Click the copy icon adjacent to any algorithm (e.g. SHA-256 or MD5) to copy the hash.' },
    ],
    features: [
      'Multi-algorithm calculation: MD5, SHA-1, SHA-256, SHA-384, SHA-512',
      'Hardware-accelerated execution via browser Web Crypto API',
      'Uppercase and lowercase hexadecimal formatting switch',
      'Individual copy buttons with animated confirmation checkmarks',
      'Zero server dependencies: private tokens and passwords never leave memory',
    ],
    faqs: [
      { question: 'Can a cryptographic hash be decrypted or reversed?', answer: 'No. Cryptographic hash functions are one-way mathematical operations. They produce fixed-length fingerprints and cannot be mathematically reversed back into the original input.' },
      { question: 'Which hash algorithm is recommended for modern security?', answer: 'SHA-256 and SHA-512 are industry standards for digital signatures, password verification, and blockchain architectures. MD5 and SHA-1 are cryptographically broken and should only be used for legacy checksum comparisons.' },
      { question: 'Are my passwords or strings stored on your server?', answer: 'Never. Web Crypto API executes directly within your local browser engine sandbox. Nothing is transmitted over the internet.' },
    ],
  },
  {
    id: 'uuid-generator',
    slug: 'uuid-generator',
    name: 'UUID / GUID Generator',
    shortDescription: 'Generate cryptographically random UUID v4 identifiers in bulk (1-100) with custom hyphen and case options.',
    category: 'developer',
    categoryName: 'Developer & Code',
    iconName: 'Fingerprint',
    badge: 'Crypto-Secure',
    popular: false,
    keywords: ['uuid generator', 'guid generator', 'random uuid v4', 'bulk uuid generator', 'unique identifier tool'],
    metaTitle: 'Bulk UUID / GUID v4 Generator - Free & Cryptographically Secure',
    metaDescription: 'Generate random UUID v4 and GUID unique identifiers individually or in bulk. Customize hyphens, uppercase or lowercase, and copy with one click.',
    longDescription: 'Generate RFC 4122 compliant Version 4 Universally Unique Identifiers (UUIDs) with cryptographically secure pseudo-random number generation via window.crypto. getRandomValues. Whether seeding relational databases, configuring distributed queue message IDs, or testing software APIs, our generator lets you batch produce up to 100 unique identifiers simultaneously with customizable hyphen formatting, uppercase or lowercase letter casing, and instant clipboard export.',
    howToSteps: [
      { step: 1, title: 'Select Batch Quantity', text: 'Pick how many UUIDs you need to generate (from 1 up to 100).' },
      { step: 2, title: 'Configure Formatting', text: 'Toggle hyphens (standard 8-4-4-4-12 format) and uppercase or lowercase letters.' },
      { step: 3, title: 'Generate & Copy', text: 'Click Generate to refresh the list, then copy all identifiers or download as a text file.' },
    ],
    features: [
      'Cryptographically secure random values via native crypto.randomUUID()',
      'Batch generation from 1 up to 100 UUIDs per generation cycle',
      'Customizable options: hyphens included/excluded, uppercase/lowercase',
      'One-tap copy for entire lists or individual identifier rows',
      'Instant text file download for database seeding',
    ],
    faqs: [
      { question: 'What is a Version 4 UUID?', answer: 'A Version 4 UUID is a 128-bit identifier generated using cryptographically strong pseudo-random numbers. There are approximately 5.3 x 10^36 possible combinations, rendering collisions practically impossible.' },
      { question: 'Is a GUID the same as a UUID?', answer: 'GUID (Globally Unique Identifier) is Microsoft term for the UUID standard. For Version 4 random implementations, they are functionally identical.' },
      { question: 'Are the generated UUIDs truly unique?', answer: 'Yes. Generating random values via the browser Web Crypto API guarantees high entropy randomness that satisfies international cryptographic standards.' },
    ],
  },
  {
    id: 'timestamp-converter',
    slug: 'timestamp-converter',
    name: 'Unix Timestamp Converter',
    shortDescription: 'Convert Unix epoch timestamps to human-readable dates (UTC & Local) and date-times to timestamps with live clock.',
    category: 'developer',
    categoryName: 'Developer & Code',
    iconName: 'Clock',
    badge: 'Live Clock',
    popular: true,
    keywords: ['unix timestamp converter', 'epoch converter', 'unix time to date', 'date to timestamp', 'epoch time tool'],
    metaTitle: 'Unix Timestamp & Epoch Converter - UTC & Local Time',
    metaDescription: 'Convert Unix timestamps in seconds or milliseconds to human-readable dates (Local & UTC), and convert dates back to epoch time with live clock.',
    longDescription: 'Unix timestamps represent the elapsed seconds since January 1, 1970 00:00:00 UTC (the Unix Epoch). Our Unix Timestamp Converter facilitates instantaneous two-way conversion between numerical timestamps (in seconds or milliseconds) and human-friendly calendar timestamps. View converted dates in your local browser timezone, Greenwich Mean Time (UTC), ISO 8601 strings, and relative descriptions (e.g. "3 hours ago"), complemented by a live ticking epoch clock.',
    howToSteps: [
      { step: 1, title: 'Input Timestamp or Date', text: 'Enter an integer timestamp in seconds/milliseconds, or pick a date-time from the calendar selector.' },
      { step: 2, title: 'Inspect Multi-Format Dates', text: 'Review the instant breakdown showing Local Time, UTC Time, ISO 8601, and relative offsets.' },
      { step: 3, title: 'Copy Values', text: 'Click any format badge to copy the formatted string directly to your clipboard.' },
    ],
    features: [
      'Live ticking current Unix Epoch clock with one-click "Now" button',
      'Auto-detects whether input is in seconds (10 digits) or milliseconds (13 digits)',
      'Simultaneous output: Local Timezone, UTC, ISO 8601, and RFC 2822 format',
      'Relative human-readable elapsed time (e.g. "In 2 days", "5 months ago")',
      'Interactive date and time picker for reverse conversion back into epoch',
    ],
    faqs: [
      { question: 'What is the Unix Epoch?', answer: 'The Unix Epoch is the milestone timestamp 0, corresponding to midnight on January 1, 1970 UTC. Most computer operating systems track time as seconds elapsed from this point.' },
      { question: 'What is the Year 2038 problem?', answer: 'Systems storing timestamps as signed 32-bit integers will overflow on January 19, 2038. Modern JavaScript and 64-bit systems utilize 64-bit floating point numbers, safely supporting dates hundreds of thousands of years into the future.' },
      { question: 'How can I tell seconds apart from milliseconds?', answer: 'Standard Unix timestamps in seconds are currently 10 digits long (e.g., 1700000000), while timestamps in milliseconds have 13 digits (e.g., 1700000000000).' },
    ],
  },
  {
    id: 'url-encoder-decoder',
    slug: 'url-encoder-decoder',
    name: 'URL Encoder & Decoder',
    shortDescription: 'Encode and decode URLs, query parameters, and URI components with parameter key-value table breakdown.',
    category: 'developer',
    categoryName: 'Developer & Code',
    iconName: 'Link',
    badge: 'URI Tools',
    popular: false,
    keywords: ['url encoder', 'url decoder', 'encodeURIComponent online', 'percent encoding', 'url parameter parser'],
    metaTitle: 'URL Encoder & Decoder - Percent Encoding & Query Parser',
    metaDescription: 'Encode and decode URLs and URI query parameters with percent-encoding support. Parse URL query strings into an organized key-value table.',
    longDescription: 'Special characters such as spaces, ampersands, question marks, and non-ASCII glyphs must be percent-encoded when passed inside web URLs to prevent broken endpoints and HTTP 400 Bad Request errors. Our URL Encoder & Decoder translates between human-readable strings and RFC 3986 percent-encoded characters. In addition to standard whole-URL and URI component encoding, the tool parses complete web links into an organized visual query parameter inspection table.',
    howToSteps: [
      { step: 1, title: 'Choose Mode', text: 'Select either "Encode" or "Decode" mode depending on your starting data.' },
      { step: 2, title: 'Paste URL or Component', text: 'Enter the URL query string or parameter payload into the editor.' },
      { step: 3, title: 'Inspect & Copy', text: 'Copy the transformed URI string or review the extracted query parameters in the breakdown table.' },
    ],
    features: [
      'Bidirectional URL encoding and decoding adhering to RFC 3986',
      'Supports full URI mode (encodeURI) and component mode (encodeURIComponent)',
      'Interactive query parameter table extracting keys and values automatically',
      'Handles multilingual international characters and symbols cleanly',
      '100% client-side with immediate execution',
    ],
    faqs: [
      { question: 'What is percent-encoding?', answer: 'Percent-encoding represents reserved or unsafe characters using a % followed by two hexadecimal digits representing the character ASCII/UTF-8 byte value (e.g. space becomes %20).' },
      { question: 'What is the difference between encodeURI and encodeURIComponent?', answer: 'encodeURI preserves functional URL structure characters like ://?&=, while encodeURIComponent encodes everything except alphanumeric characters so a string can be safely passed as a single query parameter.' },
      { question: 'Can I decode broken tracking URLs?', answer: 'Yes. Simply paste the tracking link into Decode mode to strip out nested %2F and %3F characters and reveal the underlying target web address.' },
    ],
  },
  {
    id: 'color-palette-gradient',
    slug: 'color-palette-gradient',
    name: 'Color Picker & Palette Generator',
    shortDescription: 'Inspect HEX, RGB, HSL, CMYK colors, generate complementary palettes, and build copyable CSS gradients.',
    category: 'developer',
    categoryName: 'Developer & Code',
    iconName: 'Palette',
    badge: 'Design Suite',
    popular: true,
    keywords: ['color picker', 'palette generator', 'css gradient generator', 'hex to rgb', 'hsl color tool'],
    metaTitle: 'Color Picker, Palette & CSS Gradient Generator',
    metaDescription: 'Pick colors, convert between HEX, RGB, HSL, and CMYK, generate harmonious color harmonies, and build custom CSS gradients with one-click copy.',
    longDescription: 'A versatile visual workstation for UI designers, web developers, and digital illustrators. Select colors using native color wheels, input raw HEX, RGB, or HSL values, and view instant mathematical conversions across all primary digital color spaces including print CMYK. Automatically generate color harmony palettes (complementary, analogous, triadic, and monochromatic schemes) and design two-stop or three-stop linear and radial CSS gradients with copy-ready code.',
    howToSteps: [
      { step: 1, title: 'Select Base Color', text: 'Use the interactive color picker or type in your HEX, RGB, or HSL color code.' },
      { step: 2, title: 'Explore Harmonious Palettes', text: 'Browse mathematically computed complementary, analogous, and triadic palettes.' },
      { step: 3, title: 'Design Gradients & Copy CSS', text: 'Customize angles and color stops in the gradient builder and copy the pure CSS snippet.' },
    ],
    features: [
      'Universal color conversions: HEX, RGB, HSL, and CMYK',
      'Automated color harmony palettes: Complementary, Triadic, Analogous, Monochromatic',
      'Visual CSS Linear and Radial Gradient builder with angle and position sliders',
      'One-click CSS code generation with cross-browser compatibility',
      'Color contrast luminance indicator for accessibility testing',
    ],
    faqs: [
      { question: 'What is the difference between RGB and CMYK?', answer: 'RGB is an additive color model utilized for digital monitors and phone screens, while CMYK is a subtractive four-color model used for physical commercial printing inks.' },
      { question: 'What are complementary colors?', answer: 'Complementary colors are pairs situated directly opposite each other on the color wheel (180 degrees apart), delivering vibrant visual contrast when paired together in UI design.' },
      { question: 'Can I copy the gradient code directly into Tailwind or CSS?', answer: 'Yes, the tool outputs standard standard CSS background: linear-gradient(...) syntax that can be pasted directly into any stylesheet or inline style.' },
    ],
  },
  {
    id: 'css-minifier',
    slug: 'css-minifier',
    name: 'CSS Minifier & Beautifier',
    shortDescription: 'Minify CSS stylesheets to reduce bandwidth or beautify messy CSS with clean indentation and syntax formatting.',
    category: 'developer',
    categoryName: 'Developer & Code',
    iconName: 'Code2',
    badge: 'Performance',
    popular: false,
    keywords: ['css minifier', 'beautify css', 'css compressor', 'minify stylesheet', 'clean css code'],
    metaTitle: 'CSS Minifier & Beautifier - Clean & Compress CSS',
    metaDescription: 'Minify CSS stylesheets to reduce file sizes or beautify minified CSS code into readable, structured rules. 100% client-side and free.',
    longDescription: 'Optimizing stylesheet delivery is crucial for achieving high Google PageSpeed Insights and Core Web Vitals scores. Our CSS Minifier strips unnecessary comments, trailing whitespace, duplicate semicolons, and empty rule sets, drastically shrinking your production CSS footprint. Need to inspect a minified production stylesheet? Switch to Beautify mode to uncompress dense CSS into cleanly indented, legible blocks formatted with two-space hierarchies.',
    howToSteps: [
      { step: 1, title: 'Paste CSS Code', text: 'Paste your stylesheet code into the source window or load our sample CSS.' },
      { step: 2, title: 'Choose Minify or Beautify', text: 'Click "Minify CSS" to condense code or "Beautify CSS" to restore clean indentations.' },
      { step: 3, title: 'Review Stats & Download', text: 'Check the calculated bytes saved and compression percentage, then copy or download the stylesheet.' },
    ],
    features: [
      'High-performance minification eliminating extraneous comments, whitespace, and semicolons',
      'Beautifier module indenting selectors and declarations into readable CSS blocks',
      'Detailed efficiency metrics: original size, compressed size, and percentage reduction',
      'Instant copy-to-clipboard and file download as .min.css or .css',
      'Completely client-side with no code sent across servers',
    ],
    faqs: [
      { question: 'Why should I minify my CSS files?', answer: 'Minifying CSS reduces file transfer weight across network connections, helping browsers parse stylesheets faster and decreasing First Contentful Paint (FCP) latency.' },
      { question: 'Will minifying break CSS variables or calc() expressions?', answer: 'No. The minifier preserves vital modern CSS constructs including CSS Custom Properties (--variable-name), calc() operations, and media queries.' },
      { question: 'Can I format minified vendor libraries back to readable code?', answer: 'Yes, clicking "Beautify CSS" automatically splits declarations across clean indented lines for straightforward debugging.' },
    ],
  },
  {
    id: 'lorem-ipsum-generator',
    slug: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    shortDescription: 'Generate custom placeholder filler text by paragraphs, sentences, words, or lists with one-click copy.',
    category: 'text',
    categoryName: 'Text & Content',
    iconName: 'AlignLeft',
    badge: 'Typography',
    popular: false,
    keywords: ['lorem ipsum generator', 'dummy text maker', 'placeholder text', 'latin text generator', 'sample text'],
    metaTitle: 'Lorem Ipsum Generator - Custom Dummy & Placeholder Text',
    metaDescription: 'Generate classic Latin Lorem Ipsum placeholder text for websites, wireframes, and design mockups. Custom paragraph, sentence, and word counts.',
    longDescription: 'When designing UI wireframes, typesetting magazine layouts, or scaffolding web pages, realistic dummy text helps stakeholders focus on layout, typography, and color without being distracted by readable copy. Our Lorem Ipsum Generator draws from authentic classical Latin passages by Cicero, producing natural paragraph lengths, varied sentence structures, or bulleted list items with customizable counts and one-click clipboard copying.',
    howToSteps: [
      { step: 1, title: 'Select Output Unit', text: 'Choose whether you want Paragraphs, Sentences, Words, or List Items.' },
      { step: 2, title: 'Set Quantity & Options', text: 'Adjust the count slider (1-50) and toggle whether to start with classic "Lorem ipsum dolor sit amet...".' },
      { step: 3, title: 'Copy or Download', text: 'Copy the generated placeholder text with one click or download it as a plain text file.' },
    ],
    features: [
      'Generate by paragraphs, sentences, individual words, or unordered list elements',
      'Toggle option to start with canonical "Lorem ipsum dolor sit amet, consectetur adipiscing elit"',
      'HTML markup wrapper option (wraps output in <p> or <li> tags for web developers)',
      'Character and word count monitors',
      'One-tap clipboard copy button with visual confirmation',
    ],
    faqs: [
      { question: 'What does "Lorem Ipsum" actually mean?', answer: 'Lorem Ipsum is derived from sections 1.10.32 and 1.10.33 of Cicero de Finibus Bonorum et Malorum (On the Extremes of Good and Evil), written in 45 BC. The text has been modified into nonsensical Latin since the 1500s.' },
      { question: 'Can I wrap paragraphs in HTML tags automatically?', answer: 'Yes! Toggle the "Wrap in HTML tags" switch to receive text formatted directly in <p>...</p> tags ready for web templates.' },
      { question: 'Is there a limit on how much text I can produce?', answer: 'You can generate up to 50 extensive paragraphs at once instantly inside your browser.' },
    ],
  },

  // --- TEXT & CONTENT TOOLS ---
  {
    id: 'word-counter',
    slug: 'word-counter',
    name: 'Word & Character Counter',
    shortDescription: 'Detailed text statistics including word, character, sentence, and paragraph counts, reading time, and keyword density.',
    category: 'text',
    categoryName: 'Text & Content',
    iconName: 'FileText',
    badge: 'Real-Time',
    popular: true,
    keywords: ['word counter', 'character counter', 'reading time calculator', 'keyword density checker', 'text analyzer'],
    metaTitle: 'Word Counter & Character Counter - Free Text Analyzer',
    metaDescription: 'Count words, characters (with & without spaces), sentences, paragraphs, reading time, and keyword density in real-time as you type.',
    longDescription: 'Whether drafting essays, adhering to character limits for social media posts (X/Twitter, LinkedIn, Instagram), or optimizing article lengths for search engine SEO, our Word & Character Counter provides comprehensive live typography telemetry. In addition to basic counts, the analyzer calculates estimated silent reading time, speaking presentation duration, average word length, and a top-10 keyword frequency breakdown.',
    howToSteps: [
      { step: 1, title: 'Type or Paste Content', text: 'Enter your copy into the expansive text area or paste an existing article.' },
      { step: 2, title: 'Inspect Live Metrics', text: 'Metrics for words, characters, sentences, paragraphs, and reading duration update on every keystroke.' },
      { step: 3, title: 'Analyze Keyword Density', text: 'Review the frequency chart to spot repeated words and optimize your text flow.' },
    ],
    features: [
      'Instant counts: Words, Characters (with spaces), Characters (no spaces), Sentences, Paragraphs',
      'Estimated silent reading time (based on 225 wpm) and vocal speech duration (130 wpm)',
      'Keyword frequency table ranking the most recurring words in your copy',
      'Social media platform limit meters (X/Twitter 280, Instagram 2,200, LinkedIn 3,000)',
      '100% private: your draft never leaves your local browser session',
    ],
    faqs: [
      { question: 'How is reading time calculated?', answer: 'Reading time is calculated using an industry-standard average reading speed of 225 words per minute for silent adult reading.' },
      { question: 'How does character counting work for Twitter / X?', answer: 'The tool provides a dedicated platform meter comparing your text against the 280-character ceiling for standard X/Twitter posts.' },
      { question: 'Are my essays or sensitive articles recorded anywhere?', answer: 'No. Analysis is executed 100% locally via client-side JavaScript regex tokenizers. We never log or store your writing.' },
    ],
  },
  {
    id: 'text-case-converter',
    slug: 'text-case-converter',
    name: 'Text Case Converter',
    shortDescription: 'Transform text into UPPERCASE, lowercase, Title Case, Sentence case, camelCase, snake_case, and kebab-case.',
    category: 'text',
    categoryName: 'Text & Content',
    iconName: 'Type',
    badge: '10+ Formats',
    popular: true,
    keywords: ['text case converter', 'uppercase converter', 'title case online', 'camelcase converter', 'snake case tool'],
    metaTitle: 'Text Case Converter - UPPERCASE, Title Case, camelCase',
    metaDescription: 'Convert text between UPPERCASE, lowercase, Title Case, Sentence case, camelCase, snake_case, kebab-case, and CONSTANT_CASE with one click.',
    longDescription: 'Accidentally left Caps Lock on? Need to convert database column headers to camelCase or transform marketing headlines into Chicago Manual of Style Title Case? Our Text Case Converter instantly mutates strings across over 10 grammatical and programming formats. Experience seamless transformations between UPPERCASE, lowercase, Title Case, Sentence case, camelCase, PascalCase, snake_case, kebab-case, CONSTANT_CASE, and alternating cAsE.',
    howToSteps: [
      { step: 1, title: 'Enter Text', text: 'Type or paste the sentences, phrases, or code variable names you want to convert.' },
      { step: 2, title: 'Click Desired Case Button', text: 'Select from UPPERCASE, lowercase, Title Case, camelCase, snake_case, kebab-case, etc.' },
      { step: 3, title: 'Copy Transformed Text', text: 'Click the copy icon to copy the formatted string directly to your clipboard.' },
    ],
    features: [
      'Supports 10+ standard cases: UPPERCASE, lowercase, Title Case, Sentence case, camelCase, PascalCase, snake_case, kebab-case, CONSTANT_CASE, alternating cAsE',
      'Intelligent title casing handling common articles and prepositions',
      'Programming variable formatting for clean code refactoring',
      'One-click quick copy buttons for every case variation simultaneously',
      'Clean in-browser execution with zero network latency',
    ],
    faqs: [
      { question: 'What is Title Case?', answer: 'Title Case capitalizes the first letter of major words while keeping short articles, conjunctions, and prepositions (like "the", "and", "in", "of") lowercase unless they begin the sentence.' },
      { question: 'What is the difference between camelCase and PascalCase?', answer: 'camelCase begins with a lowercase letter and capitalizes each subsequent word (myVariableName), while PascalCase capitalizes all words including the first (MyVariableName).' },
      { question: 'What is kebab-case and snake_case used for?', answer: 'kebab-case separates words with hyphens and is standard in URLs and CSS class names, while snake_case uses underscores and is common in Python and database column naming.' },
    ],
  },
  {
    id: 'duplicate-line-remover',
    slug: 'duplicate-line-remover',
    name: 'Duplicate Line Remover & Text Sorter',
    shortDescription: 'Remove duplicate lines from text lists, sort alphabetically (A-Z or Z-A), trim whitespace, and clean blank lines.',
    category: 'text',
    categoryName: 'Text & Content',
    iconName: 'ListFilter',
    badge: 'List Cleaner',
    popular: false,
    keywords: ['duplicate line remover', 'remove duplicate lines', 'sort lines alphabetically', 'text deduplicator', 'clean list online'],
    metaTitle: 'Duplicate Line Remover & Text Sorter - Clean Lists Online',
    metaDescription: 'Deduplicate lines from text lists, sort entries alphabetically from A-Z or Z-A, trim leading/trailing whitespace, and remove blank lines.',
    longDescription: 'Cleaning raw data lists, sorting email subscriber pools, and sanitizing extracted URL spreadsheets is fast and private with our Duplicate Line Remover & Text Sorter. The tool scans lists line-by-line, stripping identical entries while reporting exactly how many duplicates were purged. Combine deduplication with alphabetical sorting (A-Z or Z-A), natural numerical sorting, case-sensitive toggling, whitespace trimming, and empty line deletion.',
    howToSteps: [
      { step: 1, title: 'Paste Your List', text: 'Paste the multiline list of items, URLs, or entries into the input area.' },
      { step: 2, title: 'Configure Cleaning Options', text: 'Select options: Remove Duplicates, Sort Alphabetically, Trim Whitespace, or Remove Blank Lines.' },
      { step: 3, title: 'Copy Cleaned Output', text: 'Review the purged line count statistics and copy the deduplicated result.' },
    ],
    features: [
      'High-speed deduplication retaining either first occurrence order or sorted order',
      'Alphabetical sorting (A to Z and Z to A) plus natural numerical sequence sorting',
      'Case sensitivity toggle (treating "Apple" and "apple" as unique or duplicate)',
      'Trim leading and trailing whitespace from every line',
      'Detailed telemetry displaying original lines, removed lines, and final output count',
    ],
    faqs: [
      { question: 'Does removing duplicates change my list original order?', answer: 'By default, the tool preserves the original chronological order of your items, keeping only the first occurrence of each duplicate unless you explicitly select alphabetical sorting.' },
      { question: 'Is case-sensitive comparison supported?', answer: 'Yes. You can toggle case sensitivity on or off to choose whether uppercase and lowercase variations count as identical items.' },
      { question: 'Can it clean empty or whitespace-only lines?', answer: 'Yes! The "Remove Empty Lines" toggle automatically filters out blank rows and extraneous spacing.' },
    ],
  },

  // --- EVERYDAY UTILITIES ---
  {
    id: 'password-generator',
    slug: 'password-generator',
    name: 'Password Generator & Strength Meter',
    shortDescription: 'Generate strong, cryptographically secure passwords with custom length, character rules, and entropy score.',
    category: 'utility',
    categoryName: 'Everyday Utilities',
    iconName: 'KeyRound',
    badge: 'Zero Knowledge',
    popular: true,
    keywords: ['password generator', 'strong password generator', 'password strength meter', 'random password', 'secure credentials'],
    metaTitle: 'Strong Password Generator & Entropy Meter - 100% Client-Side',
    metaDescription: 'Generate cryptographically secure random passwords in your browser. Customize lengths, symbols, numbers, and test password strength and entropy.',
    longDescription: 'Weak or reused passwords remain the primary entry point for credential stuffing cyberattacks. Our browser-based Password Generator generates high-entropy, cryptographically uncrackable passwords using the native Web Cryptography API (window.crypto.getRandomValues). Customize character length from 6 to 64 characters, toggle uppercase letters, lowercase letters, numbers, and special symbols, and exclude visually ambiguous glyphs like 1, l, I, 0, and O. Features a real-time entropy calculator and strength score gauge.',
    howToSteps: [
      { step: 1, title: 'Select Password Length', text: 'Use the slider to choose desired character count (16+ recommended for strong security).' },
      { step: 2, title: 'Choose Character Sets', text: 'Enable or disable uppercase, lowercase, numbers, and symbols, or exclude ambiguous characters.' },
      { step: 3, title: 'Generate & Copy', text: 'Generate new random credentials instantly and copy to your password manager with one click.' },
    ],
    features: [
      'Cryptographically secure randomness via window.crypto.getRandomValues',
      'Granular controls: Uppercase (A-Z), Lowercase (a-z), Digits (0-9), Symbols (!@#$%)',
      'Avoid Ambiguous Characters switch (removes 1, l, I, 0, O, o)',
      'Live NIST-aligned Password Entropy calculation and crack time estimate',
      'Zero-knowledge architecture: generated passwords are never logged, stored, or transmitted',
    ],
    faqs: [
      { question: 'Is it safe to generate passwords in a web browser?', answer: 'Yes! Because this application operates 100% client-side, the random values are calculated inside your browser memory using hardware-backed cryptographic APIs. Nothing is ever sent across the network or stored in databases.' },
      { question: 'What makes a password strong?', answer: 'Length and entropy. A password of 16 characters or longer combining uppercase, lowercase, numbers, and symbols yields over 90 bits of entropy, requiring billions of years for modern supercomputers to brute-force.' },
      { question: 'What does the "Exclude Ambiguous" option do?', answer: 'It filters out characters that look identical in many fonts (such as numeral 1, lowercase l, and capital I), preventing frustrating typing mistakes when logging in manually.' },
    ],
  },
  {
    id: 'unit-converter',
    slug: 'unit-converter',
    name: 'Multi-Unit Converter',
    shortDescription: 'Convert length, weight, temperature, digital data storage, speed, area, and volume with live calculations.',
    category: 'utility',
    categoryName: 'Everyday Utilities',
    iconName: 'Scale',
    badge: 'Comprehensive',
    popular: true,
    keywords: ['unit converter', 'metric to imperial', 'length converter', 'weight converter', 'temperature converter online'],
    metaTitle: 'Multi-Unit Converter - Length, Weight, Temp & Storage',
    metaDescription: 'Convert between metric and imperial units across Length, Weight, Temperature, Digital Storage, Speed, Area, and Volume with instant calculation.',
    longDescription: 'Say goodbye to confusing mental math and unit conversion charts. Our Universal Unit Converter covers 7 major scientific and everyday conversion categories: Length, Weight/Mass, Temperature, Digital Data Storage, Speed, Area, and Volume. Switch between Metric, Imperial, and US Customary standards with instant bidirectional synchronization, high precision rounding, and a complete conversion reference matrix.',
    howToSteps: [
      { step: 1, title: 'Select Measurement Category', text: 'Choose from Length, Weight, Temperature, Digital Storage, Speed, Area, or Volume.' },
      { step: 2, title: 'Input Source Value & Units', text: 'Enter your number and select your source unit (e.g. Kilograms or Miles).' },
      { step: 3, title: 'View Converted Results', text: 'Select your target unit or review the simultaneous multi-unit comparison table below.' },
    ],
    features: [
      '7 comprehensive categories: Length, Weight, Temperature, Digital Data, Speed, Area, Volume',
      'Instant bidirectional recalculation as you type numbers',
      'Configurable decimal precision formatting (from 2 up to 8 decimal places)',
      'Multi-unit quick reference table converting the input into all sister units at once',
      'Works offline with zero server roundtrips',
    ],
    faqs: [
      { question: 'Does this converter use standard international conversion factors?', answer: 'Yes. All conversion ratios adhere to the International System of Units (SI) and NIST standards for high mathematical precision.' },
      { question: 'How is Temperature converted?', answer: 'Temperature uses non-linear affine transformations: converting between Celsius, Fahrenheit, and scientific Kelvin while properly accounting for freezing and boiling baselines.' },
      { question: 'Does Digital Storage use 1024 or 1000 multipliers?', answer: 'The tool uses standard binary (1 KB = 1024 Bytes) conventions favored in operating systems and RAM architectures.' },
    ],
  },
  {
    id: 'age-calculator',
    slug: 'age-calculator',
    name: 'Age Calculator & Birthday Countdown',
    shortDescription: 'Calculate your exact age in years, months, days, hours, and minutes, plus a countdown to your next birthday.',
    category: 'utility',
    categoryName: 'Everyday Utilities',
    iconName: 'Calendar',
    badge: 'Exact Days',
    popular: false,
    keywords: ['age calculator', 'exact age in days', 'birthday countdown', 'calculate age from birth date', 'chronological age'],
    metaTitle: 'Age Calculator - Exact Years, Months, Days & Next Birthday',
    metaDescription: 'Calculate your exact chronological age in years, months, weeks, days, hours, and minutes. See the weekday you were born and countdown to your next birthday.',
    longDescription: 'Curious about your exact chronological age or calculating milestone age requirements for legal forms, retirement planning, or sports leagues? Our Age Calculator calculates your precise age down to the day, accounting for leap years and variable month lengths. View your total lifetime breakdown in total months, weeks, days, hours, and minutes, discover the day of the week you were born, and see the exact days remaining until your next celebration.',
    howToSteps: [
      { step: 1, title: 'Select Date of Birth', text: 'Pick your birth year, month, and day using the date picker or input fields.' },
      { step: 2, title: 'Select Reference Date', text: 'Default is today date, or pick a custom future/past date for comparison.' },
      { step: 3, title: 'Review Life Statistics', text: 'Inspect the detailed breakdown of years, months, days, total days lived, and next birthday countdown.' },
    ],
    features: [
      'Exact age breakdown: Years, Months, Days, Hours, and Minutes',
      'Total lifetime metrics: Total Days lived, Total Weeks, Total Hours, and Total Heartbeats estimate',
      'Day of the week of birth (e.g. "You were born on a Tuesday")',
      'Interactive Next Birthday countdown display showing months and days remaining',
      '100% private: birthdates are processed in memory and never saved',
    ],
    faqs: [
      { question: 'How does the calculator handle leap years?', answer: 'The calculation algorithm accounts for Gregorian calendar leap years (every 4 years with century exceptions), ensuring exact day counts.' },
      { question: 'Can I calculate my age on a specific past or future date?', answer: 'Yes. You can override the "Calculate Age At" date to determine how old you were on a historical date or will be at retirement.' },
      { question: 'Is my birth date recorded or shared?', answer: 'Never. All calculations run strictly in your web browser via local JavaScript Date objects. No data leaves your machine.' },
    ],
  },
  {
    id: 'bmi-calculator',
    slug: 'bmi-calculator',
    name: 'BMI Calculator (Body Mass Index)',
    shortDescription: 'Calculate Body Mass Index using Metric or Imperial measurements with WHO category gauge and ideal weight range.',
    category: 'utility',
    categoryName: 'Everyday Utilities',
    iconName: 'Activity',
    badge: 'Health Metric',
    popular: true,
    keywords: ['bmi calculator', 'body mass index', 'calculate bmi metric', 'calculate bmi imperial', 'healthy weight range'],
    metaTitle: 'BMI Calculator - Body Mass Index with WHO Weight Categories',
    metaDescription: 'Calculate your Body Mass Index (BMI) using metric (cm/kg) or imperial (feet/inches/lbs) units. View your WHO classification and healthy weight range.',
    longDescription: 'Body Mass Index (BMI) is an internationally recognized screening metric established by the World Health Organization (WHO) to evaluate weight categories in adult populations. Our BMI Calculator supports both Metric (centimeters and kilograms) and Imperial (feet, inches, and pounds) inputs. Receive an instant visual gauge indicating where your score sits across Underweight, Normal Weight, Overweight, and Obese brackets, paired with a calculated healthy weight range tailored to your height.',
    howToSteps: [
      { step: 1, title: 'Select Unit System', text: 'Choose between Metric (cm & kg) or Imperial (feet, inches & lbs).' },
      { step: 2, title: 'Enter Height & Weight', text: 'Input your height and current body weight into the respective fields.' },
      { step: 3, title: 'Review Category & Healthy Range', text: 'Check your calculated BMI number, the colored category dial, and your target healthy weight range.' },
    ],
    features: [
      'Dual unit systems: Metric (centimeters, kilograms) and Imperial (feet, inches, pounds)',
      'Visual BMI spectrum bar marking Underweight (<18.5), Normal (18.5-24.9), Overweight (25-29.9), and Obese (30+)',
      'Tailored healthy weight range calculation for your exact height',
      'Prime BMI factor indication and category explanation',
      '100% confidential: personal biometric data never leaves your computer',
    ],
    faqs: [
      { question: 'What is a normal BMI score?', answer: 'According to the World Health Organization (WHO), a BMI between 18.5 and 24.9 falls within the healthy, normal weight range for adult men and women.' },
      { question: 'Does BMI distinguish between muscle mass and fat?', answer: 'BMI is a general screening indicator based purely on height and weight. Athletes with high muscle mass may register higher BMI scores without excess adipose tissue.' },
      { question: 'What is the formula for calculating BMI?', answer: 'In metric: BMI = weight (kg) / [height (m)]^2. In imperial: BMI = [weight (lbs) x 703] / [height (inches)]^2.' },
    ],
  },
  {
    id: 'percentage-calculator',
    slug: 'percentage-calculator',
    name: 'Percentage Calculator',
    shortDescription: 'Solve common percentage calculations: What is X% of Y, X is what % of Y, and percentage increase/decrease.',
    category: 'utility',
    categoryName: 'Everyday Utilities',
    iconName: 'Percent',
    badge: 'Instant Math',
    popular: false,
    keywords: ['percentage calculator', 'percent increase calculator', 'what percent of', 'calculate percentage online', 'discount calculator'],
    metaTitle: 'Percentage Calculator - Percentage Increase, Decrease & Share',
    metaDescription: 'Calculate percentages easily: find X% of Y, what percent X is of Y, and percentage change (increase or decrease) between two values.',
    longDescription: 'Whether computing sales tax, estimating retail store discounts, tracking investment returns, or calculating grade percentages, percentage math is a daily necessity. Our Percentage Calculator solves the 3 most common real-world percentage formulas in one intuitive interface: 1) What is X% of Y? 2) X is what percentage of Y? and 3) What is the percentage increase or decrease from value A to value B?',
    howToSteps: [
      { step: 1, title: 'Select Calculation Mode', text: 'Choose which percentage formula corresponds to your problem.' },
      { step: 2, title: 'Enter Numbers', text: 'Fill in the two input values into the calculation fields.' },
      { step: 3, title: 'View Result & Formula', text: 'See the exact calculated percentage answer along with a step-by-step mathematical explanation.' },
    ],
    features: [
      '3 core percentage modes covering 99% of daily business and school calculations',
      'Real-time calculation updating instantly as you type numbers',
      'Percentage increase or decrease auto-detector with color-coded difference indicators',
      'Step-by-step mathematical working shown for each result',
      'One-tap copy button for fast spreadsheet entry',
    ],
    faqs: [
      { question: 'How do you calculate percentage increase or decrease?', answer: 'Subtract the old value from the new value, divide by the original value, and multiply by 100: ((New - Old) / Old) x 100.' },
      { question: 'Can this be used for sales discounts?', answer: 'Yes! To calculate a 25% discount on an $80 item, use "What is 25% of 80" ($20 discount), meaning your final price is $80 - $20 = $60.' },
      { question: 'Does it support negative numbers and decimals?', answer: 'Yes, all calculation engines support negative values and arbitrary decimal precision.' },
    ],
  },
];
